#THEME

# Primary accent for interactive elements
primaryColor = '#e54ed0'

# Background color for the main content area
backgroundColor = '#00076f'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#ffe4f2'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"